apiVersion: apps/v1
kind: Deployment
metadata:
  name: days-since
spec:
  replicas: 1
  selector:
    matchLabels:
      app: days-since
  template:
    metadata:
      labels:
        app: days-since
    spec:
      containers:
        - name: days-since
          image: docker.io/keanuwatts/theclusterflux:DaysSince
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: days-since
spec:
  selector:
    app: days-since
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: days-since
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - days-since.theclusterflux.com
    secretName: theclusterflux
  rules:
  - host: days-since.theclusterflux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: days-since
            port:
              number: 8080