version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - IS_LOCAL=true
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - days-since-network

  mongodb:
    image: mongo:7
    ports:
      - "27016:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - days-since-network

volumes:
  mongodb_data:

networks:
  days-since-network:
    driver: bridge
